### ISSUE TITLE
Trouble building on Snow Leopard

### ISSUE THREAD

**Issue by tarcieri** [jbarnette/johnson#12] opened 2009-08-30 18:01 UTC
<pre><code>cc -o Darwin_DBG.OBJ/jsprf.o -c -Wall -Wno-format -MMD -g3 -DXP_UNIX -DSVR4 -DSYSV -D_BSD_SOURCE -DPOSIX_SOURCE -DDARWIN -DX86_LINUX  -DDEBUG -DDEBUG_root -DEDITLINE -IDarwin_DBG.OBJ  jsprf.c
jsprf.c: In function ‘BuildArgArray’:
jsprf.c:644: error: incompatible types in assignment</code></pre>

**Comment by tarcieri** [comment] 2009-08-31 19:03
Here's the patch included with MacPorts for Spidermonkey:

<pre><code>--- jsprf.c.orig        2009-07-26 12:32:01.000000000 -0700
+++ jsprf.c     2009-07-26 12:33:12.000000000 -0700
@@ -58,6 +58,8 @@
 */
 #ifdef HAVE_VA_COPY
 #define VARARGS_ASSIGN(foo, bar)        VA_COPY(foo,bar)
+#elif defined(va_copy)
+#define VARARGS_ASSIGN(foo, bar)        va_copy(foo,bar)
 #elif defined(HAVE_VA_LIST_AS_ARRAY)
 #define VARARGS_ASSIGN(foo, bar)        foo[0] = bar[0]
 #else
</code></pre>

**Comment by tarcieri** [comment] 2009-08-31 20:41
extconf.rb needs to be changed to use the x86_64 architecture on Snow Leopard.  After these two changes I was able to get it to build on Snow Leopard.

I can make these changes in a git repo if you like, but I did it all gimpily and am afraid it might break compatibility on versions of OS X prior to Snow Leopard.

**Comment by rantler** [comment] 2009-09-15 22:06
If it helps, the HOSTTYPE environment variable contains the architecture information (i.e. "x86_64")

**Comment by jbarnette** [comment] 2009-09-16 04:51
Snow Leopard folks, could you try building master? e07a90c8 should make a difference.

**Comment by jbarnette** [comment] 2009-09-27 22:17
Okay, reports are that the problem is fixed. Closing.

**Closed as completed by jbarnette** 2009-09-27 22:17 UTC

**Comment by alexthewilde** [comment] 2009-10-16 01:58
I'm lost with this same issue on Snow Leopard.

didn't help either:

sudo env HOSTTYPE="x86_64" gem install johnson
sudo env ARCHFLAGS="-arch x86_64" gem install johnson

@tarcieri
could you share a few more details how you got it running on your SL?

**Comment by akralj** [comment] 2009-11-01 10:38
i have the same problem the alexwilde. so could somebody of you great people, write out a short desc how to build it on sl. do i have to patch jsprf.c.
which to changes do I have to make in extconf.rb. tried: 
ENV["ARCHFLAGS"] = "-arch x86_64"
does not work
thanks a lot for your time
atmamurti

**Comment by jeezs** [comment] 2009-11-04 16:47
Hello, 
I've juste try to install the Johnson gem on Snow leopard with no success.
I am a beginner , unfortunately I don't know what to do to make it work.
I try to install it on Snow leopard 10.6.1 with Ruby 1.8.7
If someone can help me.
Thanks very much
